version: '3'
services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookscrud
    ports:
      - '5432:5432'
    volumes: 
      - ./db-data/:/var/lib/postgresql/data/
  nextjs:
    image: apka
    build:
      context: . 
      dockerfile: "./src/app/Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: "on-failure: 5"
    environment:
    - PORT=3000
    - JWT_SECRET=super_secret
    - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bookscrud
    